### ISSUE TITLE
Does this use FSDP or Deepspeed? Req. for accelerate config

### ISSUE THREAD

**Issue by geekyGoku** [huggingface/distil-whisper#40]
Hi,

How's the training performed? Like was it done using FSDP or DeepSpeed?

Can you please provide Accelerate config used for training?

Thanks

**Comment by sanchit-gandhi** [comment]
There is no hard and fast rule for setting the training config: you are free to experiment with different frameworks (FSDP/DeepSpeed) and benchmark the performance that you get. Using accelerate, switching between them should be trivial: https://huggingface.co/docs/accelerate/usage_guides/deepspeed

The 'base' accelerate config used for the PyTorch experiments was:

------------------------------------------------------------------------------------------------------------------------In which compute environment are you running?
**This machine**                                                                                                            
------------------------------------------------------------------------------------------------------------------------Which type of machine are you using?                                                                                    
**No distributed training**                                                                                                 
Do you want to run your training on CPU only (even if a GPU / Apple Silicon / Ascend NPU device is available)? [yes/NO]:**No**                                                                                                                      
Do you wish to optimize your script with torch dynamo?[yes/NO]:**No**                                                       
Do you want to use DeepSpeed? [yes/NO]: **No**                                                                              
What GPU(s) (by id) should be used for training on this machine as a comma-seperated list? [all]:**0**                      
------------------------------------------------------------------------------------------------------------------------Do you wish to use FP16 or BF16 (mixed precision)?
**bf16**                                

This is the 'simplest' config you can set-up, and should be sufficient for single GPU training with reasonable batch sizes. Should you want to scale to larger global batch sizes, you can try a multi GPU set-up (to enable data parallelism).

<details>

<summary> config yaml </summary>

```yaml
compute_environment: LOCAL_MACHINE
debug: false
distributed_type: 'NO'
downcast_bf16: 'no'
gpu_ids: '0'
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

</details>
